---
abstract: 'A Simple totally OO CGI interface that is CGI.pm compliant'
author:
  - 'Andy Armstrong <andy@hexten.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Temp: '0'
  Test::Exception: '0'
  Test::More: '0'
  Test::NoWarnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CGI-Simple
no_index:
  directory:
    - t
    - inc
resources:
  repository: http://github.com/manwar/CGI--Simple.git
version: '1.280'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
